# SSH with files

from netmiko import ConnectHandler
from getpass import getpass

router_ip = open(r"D:\01 C.O.D.E\PyNetLabs_Demos\a-router.txt", 'r')

for ip_add in router_ip:
    # print(ip_add.strip())
    router_dic = {
        'ip': ip_add.strip(),
        'username': input('Enter the username: '),
        'password': getpass("Enter your password: "),
        'device_type': 'cisco_ios'
    }

    ssh = ConnectHandler(**router_dic)
    print("Connected successfully to " + ip_add)

    commands_file = open(r"D:\01 C.O.D.E\PyNetLabs_Demos\a-commands.txt", 'r')
    output_file = open(r"D:\01 C.O.D.E\PyNetLabs_Demos\a-output.txt",'a')
    output_file.write("The below information is generated by " + ip_add)

    for cmds in commands_file:
        details = ssh.send_command(cmds.strip())
        output_file.write("\n\n" + details + "\n\n")
    
    print("Output is now saved")

    commands_file.close()
    output_file.close()
    ssh.disconnect()

    print("All output is now exported successfully")

router_ip.close()